#Transaction Category Mappings
#Tue Feb 04 14:25:23 EST 2025
ELFCU=ELFCU
Chase=Chase
CC\ 1=CC 1
CC\ 2=CC 2
Paycheck=Paycheck
Other\ Credits=Other Credits
Bills/Rent=Bills/Rent
Groceries=Groceries
Restaurants=Restaurants
Car/Gas=Car/Gas
Subscriptions=Subscriptions
Entertainment=Entertainment
Tech=Tech
Health/Fitness=Health/Fitness
Medical=Medical
Dispensary=Dispensary
Month=Month
Pets=Pets
Investments=Investments
Merchandise=Merchandise
Other=Other